test-deployment:
  stage: deploy
  environment:
    name: testing
  when: manual
  tags:
    - kchain
  script:
    - export KUBECONFIG=$HOME/.kube-ng/config-${CI_ENVIRONMENT_NAME:0:4}
    - chmod +x setupcc.sh
    - ./setupcc.sh v1 upgrade

prod-deployment:
  stage: deploy
  environment:
    name: production
  when: manual
  only:
    - master
    - dev
  tags:
    - kchain
  script:
    - export KUBECONFIG=$HOME/.kube-ng/config-${CI_ENVIRONMENT_NAME:0:4}
    - chmod +x setupcc.sh
    - ./setupcc.sh v1 init

