---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: servicechain-fabric
  name: chaincodeinstall
spec:
  backoffLimit: 1
  template:
    metadata:
      name: chaincodeinstall
    spec:
      restartPolicy: "Never"
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: chaincodeinstall1
          image: hyperledger/fabric-tools:1.4
          command: ["sh", "-c", "echo $GOPATH; rm -rf $GOPATH/src/*; cp -r /shared/artifacts/chaincode $GOPATH/src/; ls $GOPATH/src; peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p __CHAINCODE_NAME__/"]
          env:
            - name: CHAINCODE_NAME
              value: "__CHAINCODE_NAME__"
            - name: CHAINCODE_VERSION
              value: "__CHAINCODE_VERSION__"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org1.kbaas.kingdeeresearch.com/users/Admin@org1.kbaas.kingdeeresearch.com/msp
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org1.kbaas.kingdeeresearch.com/peers/peer0.org1.kbaas.kingdeeresearch.com/tls/ca.crt
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_ADDRESS
              value: peer0.servicechain-org1:7051
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume

        - name: chaincodeinstall2
          image: hyperledger/fabric-tools:1.4
          command: ["sh", "-c", "echo $GOPATH; rm -rf $GOPATH/src/*; cp -r /shared/artifacts/chaincode $GOPATH/src/; ls $GOPATH/src; peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p __CHAINCODE_NAME__/"]
          env:
            - name: CHAINCODE_NAME
              value: "__CHAINCODE_NAME__"
            - name: CHAINCODE_VERSION
              value: "__CHAINCODE_VERSION__"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org1.kbaas.kingdeeresearch.com/users/Admin@org1.kbaas.kingdeeresearch.com/msp
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org1.kbaas.kingdeeresearch.com/peers/peer1.org1.kbaas.kingdeeresearch.com/tls/ca.crt
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_ADDRESS
              value: peer1.servicechain-org1:7051
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume

        - name: chaincodeinstall3
          image: hyperledger/fabric-tools:1.4
          command: ["sh", "-c", "echo $GOPATH; rm -rf $GOPATH/src/*; cp -r /shared/artifacts/chaincode $GOPATH/src/; ls $GOPATH/src; peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p __CHAINCODE_NAME__/"]
          env:
            - name: CHAINCODE_NAME
              value: "__CHAINCODE_NAME__"
            - name: CHAINCODE_VERSION
              value: "__CHAINCODE_VERSION__"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org2.kbaas.kingdeeresearch.com/users/Admin@org2.kbaas.kingdeeresearch.com/msp
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org2.kbaas.kingdeeresearch.com/peers/peer0.org2.kbaas.kingdeeresearch.com/tls/ca.crt
            - name: CORE_PEER_LOCALMSPID
              value: Org2MSP
            - name: CORE_PEER_ADDRESS
              value: peer0.servicechain-org2:7051
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume

        - name: chaincodeinstall4
          image: hyperledger/fabric-tools:1.4
          command: ["sh", "-c", "echo $GOPATH; rm -rf $GOPATH/src/*; cp -r /shared/artifacts/chaincode $GOPATH/src/; ls $GOPATH/src; peer chaincode install -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -p __CHAINCODE_NAME__/"]
          env:
            - name: CHAINCODE_NAME
              value: "__CHAINCODE_NAME__"
            - name: CHAINCODE_VERSION
              value: "__CHAINCODE_VERSION__"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org2.kbaas.kingdeeresearch.com/users/Admin@org2.kbaas.kingdeeresearch.com/msp
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org2.kbaas.kingdeeresearch.com/peers/peer1.org2.kbaas.kingdeeresearch.com/tls/ca.crt
            - name: CORE_PEER_LOCALMSPID
              value: Org2MSP
            - name: CORE_PEER_ADDRESS
              value: peer1.servicechain-org2:7051
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
