---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: trustchain-fabric
  name: chaincodeupgrade
spec:
  backoffLimit: 1
  template:
    metadata:
      name: chaincodeupgrade
    spec:
      restartPolicy: "Never"
      volumes:
        - name: sharedvolume
          persistentVolumeClaim:
            claimName: shared-pvc
      containers:
        - name: chaincodeupgrade
          image: hyperledger/fabric-tools:1.4
          command: ["sh", "-c", "peer chaincode upgrade -o ${ORDERER_URL} -C ${CHANNEL_NAME} -n ${CHAINCODE_NAME} -v ${CHAINCODE_VERSION} -c '{\"Args\":[\"init\"]}'"]
          env:
            - name: CHANNEL_NAME
              value: __CHANNEL_NAME__
            - name: ORDERER_URL
              value: orderer0.trustchain-ordererorg1:7050
            - name: CHAINCODE_NAME
              value: "__CHAINCODE_NAME__"
            - name: CHAINCODE_VERSION
              value: "__CHAINCODE_VERSION__"
            - name: FABRIC_CFG_PATH
              value: /etc/hyperledger/fabric
            - name: CORE_PEER_MSPCONFIGPATH
              value: /shared/crypto-config/peerOrganizations/org1.kbaas.kingdeeresearch.com/users/Admin@org1.kbaas.kingdeeresearch.com/msp
            - name: CORE_PEER_TLS_ROOTCERT_FILE
              value: /shared/crypto-config/peerOrganizations/org1.kbaas.kingdeeresearch.com/peers/peer0.org1.kbaas.kingdeeresearch.com/tls/ca.crt
            - name: CORE_PEER_LOCALMSPID
              value: Org1MSP
            - name: CORE_PEER_ADDRESS
              value: peer0.trustchain-org1:7051
            - name: GODEBUG
              value: "netdns=go"
          volumeMounts:
            - mountPath: /shared
              name: sharedvolume
